# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6078a7083c5790d34c87441d29acb0bc38d3dff08950b034d3027f2c403745164735121f29a8b8e2b51c142d85714d839869634c01a01e6eb3c7682815008710

test:
  secret_key_base: 5f3c6a452dc368fcdcec211a549e1fe9f49fb6a182147fb652c202c241defa36592fade531b882cf13408c6ff4a60450643b3617c391ffa87610c572631dc906

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
